# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=16)),
                ('status', models.CharField(choices=[('created', 'Created'), ('awaiting_payment', 'Awaiting payment'), ('payment_detected', 'Payment detected'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=24)),
                ('payment_instructions', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='ledger.ledgertransaction')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='payments.paymenttransaction')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='payments.paymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='deposits_de_user_id_89e1ef_idx'), models.Index(fields=['status', 'expires_at'], name='deposits_de_status_5c9281_idx')],
            },
        ),
    ]
