# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPAProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. network_a', max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('adapter_path', models.CharField(help_text='Dotted path, e.g. apps.cpa.providers.network_a.NetworkAAdapter', max_length=255)),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('supports_api_sync', models.BooleanField(default=False)),
                ('supports_postback', models.BooleanField(default=True)),
                ('supports_signature', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CPAProviderHealthLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], max_length=16)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='cpa.cpaprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
