# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpa', '0001_initial'),
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'offer categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=191)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('advertiser', models.CharField(blank=True, max_length=120)),
                ('payout', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Advertiser / provider payout.', max_digits=20)),
                ('user_reward', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Configured user reward.', max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('reward_mode', models.CharField(choices=[('cash', 'Cash'), ('points', 'Points'), ('hybrid', 'Hybrid')], default='cash', max_length=16)),
                ('points_reward', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tracking_url', models.URLField(blank=True, max_length=1000)),
                ('preview_image', models.URLField(blank=True, max_length=1000)),
                ('countries', models.JSONField(blank=True, default=list, help_text='Empty = all countries')),
                ('devices', models.JSONField(blank=True, default=list)),
                ('operating_systems', models.JSONField(blank=True, default=list)),
                ('min_age', models.PositiveSmallIntegerField(default=0)),
                ('incentive_allowed', models.BooleanField(db_index=True, default=False)),
                ('traffic_source_allowed', models.JSONField(blank=True, default=list)),
                ('vpn_allowed', models.BooleanField(default=False)),
                ('proxy_allowed', models.BooleanField(default=False)),
                ('emulator_allowed', models.BooleanField(default=False)),
                ('multiple_completion_allowed', models.BooleanField(default=False)),
                ('reinstall_allowed', models.BooleanField(default=False)),
                ('daily_user_limit', models.PositiveIntegerField(default=1)),
                ('lifetime_user_limit', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('paused_by_quota', 'Paused by quota'), ('disabled_by_compliance', 'Disabled by compliance')], db_index=True, default='active', max_length=32)),
                ('is_featured', models.BooleanField(default=False)),
                ('rank_score', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='cpa.cpaprovider')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offers.offercategory')),
            ],
            options={
                'ordering': ['-rank_score', '-payout'],
            },
        ),
        migrations.CreateModel(
            name='CampaignQuota',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_global_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('hourly_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_user_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('lifetime_user_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('country_cap', models.JSONField(blank=True, default=dict, help_text='{"PK": 100}')),
                ('conversions_today', models.PositiveIntegerField(default=0)),
                ('conversions_this_hour', models.PositiveIntegerField(default=0)),
                ('conversions_lifetime', models.PositiveIntegerField(default=0)),
                ('last_hour_reset_at', models.DateTimeField(blank=True, null=True)),
                ('last_day_reset_at', models.DateTimeField(blank=True, null=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='offers.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferClick',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('click_id', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id_hash', models.CharField(blank=True, max_length=128)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='offers.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferConversion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_conversion_id', models.CharField(db_index=True, max_length=191)),
                ('payout', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('user_reward', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id_hash', models.CharField(blank=True, max_length=128)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('click', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='offers.offerclick')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='offers.offer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='cpa.cpaprovider')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_conversions', to='rewards.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferPostback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processing_result', models.CharField(blank=True, max_length=64)),
                ('processing_note', models.CharField(blank=True, max_length=255)),
                ('conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postbacks', to='offers.offerconversion')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postbacks', to='cpa.cpaprovider')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'incentive_allowed'], name='offers_offe_status_431a34_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['reward_mode'], name='offers_offe_reward__50c0f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_offer_provider_external'),
        ),
        migrations.AddIndex(
            model_name='offerclick',
            index=models.Index(fields=['user', 'offer', 'created_at'], name='offers_offe_user_id_534d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['status', 'created_at'], name='offers_offe_status_9da96d_idx'),
        ),
        migrations.AddIndex(
            model_name='offerconversion',
            index=models.Index(fields=['user', 'offer'], name='offers_offe_user_id_73195b_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerconversion',
            constraint=models.UniqueConstraint(fields=('provider', 'external_conversion_id'), name='uniq_conversion_provider_external'),
        ),
    ]
