# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_used', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('qualified', 'Qualified'), ('rejected', 'Rejected')], db_index=True, default='registered', max_length=16)),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signup_device_hash', models.CharField(blank=True, max_length=128)),
                ('fraud_flags', models.JSONField(blank=True, default=dict)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralConversion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(help_text='offer / survey / game / deposit', max_length=32)),
                ('source_reference', models.CharField(blank=True, max_length=191)),
                ('gross_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('reward_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='referrals.referral')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_conversions', to='rewards.reward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='referrals_r_referre_ebbb80_idx'),
        ),
        migrations.AddIndex(
            model_name='referralconversion',
            index=models.Index(fields=['referral', 'status'], name='referrals_r_referra_ce4556_idx'),
        ),
    ]
