# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('signup', 'Signup bonus'), ('daily_login', 'Daily login'), ('streak', 'Login streak'), ('first_offer', 'First offer'), ('first_withdrawal', 'First withdrawal'), ('deposit', 'Deposit bonus'), ('referral', 'Referral bonus'), ('campaign', 'Campaign bonus'), ('seasonal', 'Seasonal bonus')], db_index=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reward_mode', models.CharField(choices=[('points', 'Points'), ('cash', 'Cash'), ('bonus', 'Bonus wallet')], default='points', max_length=16)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=3, help_text='For deposit bonuses, e.g. 10.000 = 10% of the deposit.', max_digits=6, null=True)),
                ('max_reward', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=20, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="e.g. {'min_deposit': '5.00'}")),
                ('streak_days', models.JSONField(blank=True, default=list, help_text='Per-day rewards, e.g. [10, 15, 20, 30, 50, 75, 100]')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_claims_per_user', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='rewards.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to='bonuses.bonusrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusClaim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bonus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='bonuses.bonus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_claims', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='bonuses.bonusrule')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['user', 'rule', 'status'], name='bonuses_bon_user_id_4efa37_idx'),
        ),
    ]
