# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('vpn', 'VPN detected'), ('proxy', 'Proxy detected'), ('tor', 'TOR exit node'), ('emulator', 'Emulator'), ('multi_account', 'Multiple accounts'), ('device_reuse', 'Device reuse'), ('ip_reuse', 'IP reuse'), ('cookie_manipulation', 'Cookie manipulation'), ('fake_postback', 'Fake postback'), ('rapid_conversion', 'Rapid conversions'), ('impossible_time', 'Impossible completion time'), ('repeated_install', 'Repeated app install'), ('chargeback', 'Chargeback'), ('payment_abuse', 'Payment abuse'), ('referral_abuse', 'Referral abuse')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('false_positive', 'False positive')], db_index=True, default='open', max_length=16)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id_hash', models.CharField(blank=True, max_length=128)),
                ('action_taken', models.CharField(blank=True, max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_events_resolved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='fraud_fraud_user_id_50df08_idx'), models.Index(fields=['kind', 'severity', 'created_at'], name='fraud_fraud_kind_2c480f_idx')],
            },
        ),
    ]
