# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. nowpayments', max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('crypto', 'Crypto'), ('local', 'Local / Bank / Wallet'), ('card', 'Card')], max_length=16)),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('supports_deposits', models.BooleanField(default=True)),
                ('supports_withdrawals', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Non-secret settings. Secrets come from environment variables.')),
                ('fee_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('fee_fixed', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], db_index=True, max_length=16)),
                ('external_id', models.CharField(db_index=True, max_length=191)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=16)),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=20, null=True)),
                ('crypto_currency', models.CharField(blank=True, max_length=16)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('awaiting_payment', 'Awaiting payment'), ('detected', 'Detected'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=24)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.paymentprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'direction', 'created_at'], name='payments_pa_status_5fb97a_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_provider_external_id')],
            },
        ),
    ]
