# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('trigger', models.CharField(choices=[('user_registered', 'User registered'), ('email_verified', 'Email verified'), ('phone_verified', 'Phone verified'), ('first_deposit', 'First deposit'), ('first_game', 'First game'), ('game_milestone', 'Game milestone'), ('survey_completed', 'Survey completed'), ('offer_completed', 'Offer completed'), ('withdrawal_requested', 'Withdrawal requested'), ('withdrawal_approved', 'Withdrawal approved'), ('withdrawal_rejected', 'Withdrawal rejected'), ('referral_registered', 'Referral registered'), ('referral_converted', 'Referral converted'), ('fraud_score_changed', 'Fraud score changed'), ('campaign_quota_reached', 'Campaign quota reached'), ('provider_unavailable', 'Provider unavailable')], db_index=True, max_length=32)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="AND-ed conditions, e.g. {'risk_lt': 30}")),
                ('actions', models.JSONField(blank=True, default=list, help_text='List of {"action": "...", "params": {...}} executed in order.')),
                ('max_executions_per_user', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.automationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
