# Generated by Django 5.1.15 on 2026-09-17 19:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='e.g. /games/racing/', max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('robots', models.CharField(default='index,follow', max_length=64)),
                ('og_title', models.CharField(blank=True, max_length=160)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.URLField(blank=True, max_length=500)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SEO configuration',
                'verbose_name_plural': 'SEO configurations',
                'ordering': ['path'],
            },
        ),
    ]
