# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = evaluated first.')),
                ('source', models.CharField(choices=[('game', 'Game'), ('survey', 'Survey'), ('offer', 'Offer'), ('bonus', 'Bonus'), ('referral', 'Referral'), ('any', 'Any source')], default='any', max_length=16)),
                ('provider_code', models.CharField(blank=True, max_length=64)),
                ('campaign_type', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('user_tier', models.CharField(blank=True, max_length=16)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='e.g. {"min_payout": "5.00", "max_payout": null}')),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('points', 'Points'), ('hybrid', 'Hybrid (cash + points)')], default='cash', max_length=16)),
                ('user_percentage', models.DecimalField(blank=True, decimal_places=3, help_text='Percent of validated revenue paid to the user, e.g. 40.000', max_digits=6, null=True)),
                ('fixed_cash', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=20, null=True)),
                ('fixed_points', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('points_percentage', models.DecimalField(blank=True, decimal_places=3, help_text='Percent of validated revenue converted to points.', max_digits=6, null=True)),
                ('multiplier', models.DecimalField(decimal_places=3, default=1, max_digits=8)),
                ('max_user_reward', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=20, null=True)),
                ('requires_manual_approval', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('game', 'Game'), ('survey', 'Survey'), ('offer', 'Offer'), ('bonus', 'Bonus'), ('referral', 'Referral'), ('adjustment', 'Admin adjustment'), ('promotion', 'Promotion')], db_index=True, max_length=16)),
                ('source_reference', models.CharField(blank=True, db_index=True, help_text='e.g. offer conversion id, game session id.', max_length=191)),
                ('gross_revenue', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=20, null=True)),
                ('platform_share', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), max_digits=20, null=True)),
                ('user_reward', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('points_reward', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_approved', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='ledger.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='rewards.rewardrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='rewards_rew_user_id_6a44e5_idx'), models.Index(fields=['source', 'source_reference'], name='rewards_rew_source_313e55_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_reference__gt', '')), fields=('source', 'source_reference', 'user'), name='uniq_reward_source_ref')],
            },
        ),
    ]
