# Generated by Django 5.1.15 on 2026-09-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_reward_gross_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardrule',
            name='reward_currency',
            field=models.CharField(default='PKR', help_text='Currency the user is paid in (ADR-015: PKR by default).', max_length=8),
        ),
        migrations.AlterField(
            model_name='reward',
            name='currency',
            field=models.CharField(default='PKR', max_length=8),
        ),
    ]
