# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('adapter_path', models.CharField(help_text='Dotted path to the adapter class, e.g. apps.surveys.providers.example.ExampleProvider', max_length=255)),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('health', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=191)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('device', models.CharField(blank=True, max_length=16)),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('payout', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Provider payout (revenue).', max_digits=20)),
                ('user_reward', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='What the user receives.', max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('reward_mode', models.CharField(default='cash', max_length=16)),
                ('qualification_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('paused_by_quota', 'Paused by quota')], db_index=True, default='active', max_length=24)),
                ('daily_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('user_cap', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='surveys.surveyprovider')),
            ],
            options={
                'ordering': ['-payout'],
            },
        ),
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('disqualified', 'Disqualified'), ('abandoned', 'Abandoned'), ('invalidated', 'Invalidated')], db_index=True, default='started', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyCompletion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_completion_id', models.CharField(max_length=191)),
                ('payout', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('user_reward', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_completions', to='rewards.reward')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_completions', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='surveys.surveyprovider')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='surveys.surveysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['status', 'country'], name='surveys_sur_status_96d113_idx'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_survey_provider_external'),
        ),
        migrations.AddIndex(
            model_name='surveysession',
            index=models.Index(fields=['user', 'survey', 'status'], name='surveys_sur_user_id_379abd_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveycompletion',
            constraint=models.UniqueConstraint(fields=('provider', 'external_completion_id'), name='uniq_survey_completion_external'),
        ),
    ]
