# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('reward', 'Reward'), ('reversal', 'Reversal'), ('bonus', 'Bonus'), ('deposit', 'Deposit'), ('withdrawal_reserve', 'Withdrawal reserve'), ('withdrawal_payout', 'Withdrawal payout'), ('withdrawal_refund', 'Withdrawal refund'), ('adjustment', 'Admin adjustment'), ('fee', 'Fee'), ('conversion', 'Conversion')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=16)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, help_text="Unique external key, e.g. 'cpa:networkA:conversion123'.", max_length=191, null=True, unique=True)),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.ledgertransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Signed amount: positive credits the account.', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallets.walletaccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledgertransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['type', 'status', 'created_at'], name='ledger_ledg_type_bc068d_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='ledger_ledg_account_03d670_idx'),
        ),
    ]
