# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_reason', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('points', 'Points'), ('bonus', 'Bonus'), ('pending', 'Pending'), ('locked', 'Locked'), ('withdrawable', 'Withdrawable'), ('deposit', 'Deposit')], max_length=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('is_frozen', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='wallets.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='wallets.walletaccount')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.AddIndex(
            model_name='walletaccount',
            index=models.Index(fields=['type', 'currency'], name='wallets_wal_type_b77d8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletaccount',
            constraint=models.UniqueConstraint(fields=('wallet', 'type', 'currency'), name='uniq_wallet_account'),
        ),
    ]
