# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='not_started', max_length=16)),
                ('level', models.CharField(choices=[('none', 'None'), ('basic', 'Basic (name + DOB)'), ('full', 'Full (ID document + selfie)')], default='none', max_length=16)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=32)),
                ('document_number', models.CharField(blank=True, max_length=64)),
                ('document_front', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('document_back', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('selfie', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=191)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
