# Generated by Django 5.1.15 on 2026-09-17 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='e.g. {"min_score": 50, "account_age_days_lt": 3}')),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('rate_limit', 'Rate limit'), ('hold_reward', 'Hold reward'), ('require_verification', 'Require verification'), ('disable_offers', 'Disable offers'), ('disable_withdrawals', 'Disable withdrawals'), ('freeze_account', 'Freeze account'), ('alert_admin', 'Alert admin')], default='alert_admin', max_length=32)),
                ('score_delta', models.SmallIntegerField(default=0, help_text="Applied to the user's risk score when the rule matches.")),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['user', 'computed_at'], name='risk_risksc_user_id_f8bc81_idx')],
            },
        ),
    ]
